version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://backend:5000
    networks:
      - app-network
  backend:
    build: ./backend
    ports:
     - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge